name: SeleniumBase Automation

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run SeleniumBase Script
        run: |
          pytest sauce_demo.py
          
      - name: Generate Test Report
        run: |
          pytest --html=report.html sauce_demo.py
        continue-on-error: true

      - name: Upload Test Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html
          
      - name: Display Report URL
        run: |
          echo "Test Report URL: ${{ github.server_url }}/actions/artifacts/${{ github.run_id }}/test-report/report.html"